language: node_js
node_js: node
script:
- npm run lint
- npm run test
before_install:
  - echo -e "machine github.com\n  login $GITHUB_RELEASE_TOKEN" >> ~/.netrc
env:
  global:
  - REPO_NAME=d2l-sequence-viewer
  #GITHUB_RELEASE_TOKEN
  - secure: GLgTA1wUfx12P0M3ipbXCnkUOAcZID168h4btHZVh4gRe7oW7zzXRabSbqSs7UY6TkL99RLikq0mDRzk5mgZJl/EoxtgcErq2ex0dHh+QWiI4qccBNqtMDN0v9BLLh9ZdZcn5wUmny8J80CT3yjjFZUHRolx7XzvNr0xrex7B7vGm2qPEmgbB2x71jx+cEpPN9awCZ/ZVay/im/OIeLLEu5KTvGDiiunEg5uVcRjFl/2GsM27d5MM9947mJ+GGVQ+JoyLBi60q9GdoVQce6ceh21XaCP7gqiEnRVVe+e1p/NFt/XgeyL0Tm/MhwvKlf8KAAUrDWSfe2k3NtNSc6dP7ezHdziqNfoPFbneuWQCCH+blIEE12e9bIwROgeN+uaRtUhXuQJNiqIyh9PdHLgMradydJ3zsDeDm3aBfRF4FaRFDIgIqFD54yTljh95y1soCJXPbXZw+U/ZqLgMRLvjm6u+az7B3lmxl7CQX/uA3zXWsZRARXRRKqppVls3mGlE7kP+I7xy2QhH1SkbcihjyyrAT4tXz+buWVJrjr+0EkiV2TIEgQHGOeVsMz6NWUwDiSAJ7jE/lFiTHi3gkThapMbbb0eJpg6zYixZYzMtJobR12gVaF1sqReFsJdJYdUkYv7R147WVvY6lzmjrd9tSHGuBwZVkrsg85jJDrGWFM=
