language: node_js
node_js: node
script:
- npm run lint
- npm run test
before_install:
  - echo -e "machine github.com\n  login $GITHUB_RELEASE_TOKEN" >> ~/.netrc
env:
  global:
  - REPO_NAME=d2l-sequence-viewer
  #GITHUB_RELEASE_TOKEN
  - secure: Jaekmd6NhnUaUBMMXWK+y51hcK7lgBt/4udCwWrhxglJf8AW7l9aVABfQwCys0D1VRxTH7QQJhC/CGIGqirZ6Xk93BESJyMmZynl2Z1VcGRnVCm41gp4algAru9pa0zvt90Gv+CDSS7PmewPgrAO6aUWzuWkDYFdShGR6Ed6EcNOv3jg6KWZ813hYL4OYm+frPks9jG+iRIUUbnJmdOmyDaYbxGNh7NrUC2kf8sxQulaguKFsmwlPpOslw0yyMho+w585Q8CWAYY6RGB6iXVyXhHrOkzVp9WZjg5JQfK/SgwGUdsGkapDLrFQxkfH3XlIU4+Jn/K0SFI05V6j7Se4E6eW3XvHcsdZ/rFfncJTAac5z1dVkG5wj9D7BhyzQYXumtEfkS9FzQWdBaRbqKqnQJcDxn4OCuqHWiD28Mp44Bj33pMi2fqaNTboW+8cmcQnnJqWpuutU5lW8VHurQUdf+sgDHPFOo5LgILXLivAlO3eHZ5H3NKdlwIw7Po0YL+MKaspdUakUOhx8kHnISvPeMVk9ghsdq9AdS18otfQznlYhS+dAP4R9+/qX70DZCby73X3TsrXaWUQqkJYZxNqolcrjCpAnB3p9orTPtiV1Jbyuc/7jmq+zyDV+vWOC4dKBwyCm/yaMLJ4CmaM9JXVr2T4Q1RacECOW/FxRvRMV8=
